- name: Infra-Agil Mint - IFTO
  hosts: Mint
  become: yes
  vars:
          mylink: "/usr/bin/javaws"
          mysrc: "/opt/java/bin/javaws"
         
  - name: ATUALIZANDO REPOSITORIO
  apt:
    update-cache: yes
      
- name: Instalando pacotes essenciaisss
  become: true
  apt: 
    name: "{{ item }}"
  loop:
    - sl
    - wget
    - vlc
    - hardinfo
    - chromium-browser
    - rar
    - git
- name: Change Password user IFTO 
  hosts: all
  become: true
  vars:
    myuser: "ifto"
    mypassword: "ifto"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"

- name: Change Password user ROOT 
  hosts: all
  become: true
  vars:
    myuser: "root"
    mypassword: "ifto"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
