---
- name: win_services module demo
  hosts: all
  become: false
  gather_facts: true
#  vars:
#    - services:
#        - SysMain
#        - DiagTrack

  tasks:
    - name: Removendo Servicos
      ansible.windows.win_service:
          name: "DiagTrack"
          state: absent
