---
- name: win_services module demo
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Ensure Chocolatey installed from internal repo
      win_chocolatey:
        name: chocolatey
        state: present
        source: http://internal/odata/repo/ChocolateyInstall.ps1
