- name: Playbook Reinicializacao de Maquinas
  hosts: all
  tasks:
    - name: restart_windows
      win_reboot:
        msg: "Seu computador sera reiniciado em 30 segundos. Salve seu trabalho."
        pre_reboot_delay: 30
        post_reboot_delay: 40
