---
- hosts: all
  #  become: runas
  #  gather_facts: false

  vars:
  - packages:
    - netbeans
    - winscp  

  tasks:
  - name: Instalando Programas Especificos - IFTO 
    win_chocolatey:
      name: "{{ packages }}"
      state: present
