- name: Desligar computador
  hosts: all
  gather_facts: no
  tasks:
  - name: Aguardar confirmação do usuário
    pause:
      prompt: "Tem certeza que deseja desligar o computador? (S/N)"
      echo: true
    register: confirm
    async: 15
    poll: 0
    ignore_errors: true
  - name: Desligar computador remoto
    win_shell: Stop-Computer -Force
    when: confirm.user_input | lower == 's'
