---
- hosts: all
  #  become: runas
  #  gather_facts: false

  vars:
  - packages:
    - notepadplusplus
    - googlechrome
    - teracopy
    - 7zip
    - firefox
    - libreoffice-fresh
    - foxitreader
    - jre8
    - chrome-remote-desktop-chrome
    - chrome-remote-desktop-host
    - dotnetfx
    - cutepdf
    - vlc
    - anydesk
    - python
    - glpi-agent
  - programas:
      HP:
        - HP Support Assistant
        - HP Security Manager
      Dell:
        - dellcommandupdate
        - supportassist
  tasks:
  - name: Instalando Programas Essenciais - IFTO
    win_chocolatey:
      name: "{{ packages }}"
      state: present

  - name: Verificando o System Vendor da máquina
    win_shell: |
      $vendor = Get-WmiObject -Class:Win32_ComputerSystem | Select-Object -ExpandProperty Manufacturer
       Write-Host "$vendor"
    register: system_vendor

  - name: Instalando programas do System Vendor
    win_chocolatey:
      name: "{{ item }}"
      state: present
    with_items: "{{ programas[system_vendor.stdout.split()[0]] }}"

