---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: false
    #vars:
    #- packages:
    #  - Microsoft.SkypeApp

  tasks:
    - name: remove windows apps as user
      ansible.windows.win_package:
        product_id: "{{ item }}"
        state: absent
      loop:
        - 'Microsoft.MicrosoftOfficeHub'
        - 'Microsoft.MixedReality.Portal'
        - 'Microsoft.Office'
        - 'Microsoft.Office.*'
        - 'Microsoft.Office.OneNote'
        - 'Microsoft.Office.OneDrive'
        - 'Microsoft.People'
        - 'Microsoft.SkypeApp'
        - 'Microsoft.WindowsStore'
        - 'Microsoft.ZuneVideo'
        - 'O365HomePremRetail'
        - 'officeproplus2013'
        - 'office365business'
        - 'office365proplus'
        - 'office365homepremium'
        - 'O365ProPlusRetail'
        - 'O365BusinessRetail'
        - 'O365SmallBusPremRetail'
        - 'O365ProPlusRetail'

