---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: false
  vars:
    - packages:
       - notepadplusplus
       - googlechrome
       - teracopy
       - 7zip
       - firefox
       - libreoffice-fresh
       - foxitreader
       - jre8
       - chrome-remote-desktop-chrome
       - chrome-remote-desktop-host
       - dotnetfx
       - cutepdf
       - vlc
       - dellcommandupdate
       - anydesk

  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present
