- hosts: all
  gather_facts: yes
  vars:
    win_interface_name: "{{ 'Ethernet' }}"
  tasks:
    - name: Obter informações do sistema
      win_shell: Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter "IPEnabled = True" |
                  Where-Object { $_.Caption -like '*{{ win_interface_name }}*' } |
                  Select-Object -First 1 |
                  Select-Object -Property DNSHostName, IPAddress, MACAddress |
                  ConvertTo-Json -Compress
      register: output

    - name: Extrair informações
      set_fact:
        hostname: "{{ output.stdout | from_json | json_query('DNSHostName') }}"
        ip_address: "{{ output.stdout | from_json | json_query('IPAddress[0]') }}"
        mac_address: "{{ output.stdout | from_json | json_query('MACAddress') }}"

    - name: Gravar informações em um arquivo
      lineinfile:
        path: c:/arquivo.txt
        line: "Nome da máquina: {{ hostname }}, IP: {{ ip_address }}, MAC: {{ mac_address }}"


