- hosts: All
  vars:
    message: "A m치quina ser치 reiniciada em 30 Segundos. Salve seu trabalho."
  tasks:
    - name: Mostrar mensagem na tela
      win_msg:
        title: "Reiniciando M치quina"
        body: "{{ message }}"
        timeout: 30
    - name: Reiniciar M치quina
      win_reboot:
