---
- name: Ingressar Maquinas no AD
  hosts: win
  gather_facts: no
    #  vars: 
    #    - nome_da_maquina: "{{ ansible_netbios_name }}"

  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: ifto.local
      hostname: "REI-020330"
      domain_admin_user: "1819630@ifto.local"
      domain_admin_password: "#1404@Lice"
      domain_ou_path: "OU=IFTO,DC=ifto,DC=local"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
